spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://13.210.70.9:3306/planit
    username: backend
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: planit745@gmail.com
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

logging:
  level:
    org.springframework.web: INFO
    org.springframework.web.servlet.DispatcherServlet: INFO
