spring:
  application:
    name: planit

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    hikari:
      connectionTimeout: 60000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://docker-mysql-test.cl82gmc8wwsn.ap-southeast-2.rds.amazonaws.com:3306/planit?rewriteBatchedStatements=true
    username: user
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: planit745@gmail.com
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
server:
  port: 9090

jwt:
  secret: ${JWT_SECRET}

google:
  api:
    key: ${GOOGLE_API_KEY}

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: TRACE

aws:
  s3:
    accessKey: ${AWS_ACCESS_KEY_ID}
    secretKey: ${AWS_SECRET_ACCESS_KEY}
    region: ${AWS_REGION}
    bucketName: ${AWS_S3_BUCKET_NAME}

