spring:
  config:
    activate:
      on-profile: dev

  datasource:
    hikari:
      connectionTimeout: 60000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.27.120.252:3306/planit
    username: backend
    password: planIt@0331

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: planit745@gmail.com
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

jwt:
  secret: ${JWT_SECRET}

google:
  api:
    key: ${GOOGLE_API_KEY}

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: TRACE

springdoc:
  swagger-ui:
    server-url: http://3.27.120.252:8080

aws:
  s3:
    accessKey: ${AWS_ACCESS_KEY_ID}
    secretKey: ${AWS_SECRET_ACCESS_KEY}
    region: ${AWS_REGION}
    bucketName: ${AWS_S3_BUCKET_NAME}
