# 1. 베이스 이미지 설정
FROM openjdk:21-jdk-slim

WORKDIR /app

# 3. 프로젝트 파일 복사
COPY gradlew gradle /app/planit/
COPY build.gradle settings.gradle /app/planit/
COPY src /app/planit/src

# 4. 빌드
RUN apt-get update && apt-get install -y bash
RUN chmod +x planit/gradlew
RUN ./planit/gradlew build -x test --no-daemon

CMD ["java", "-jar", "planit/build/libs/planit.jar"]
